Completed Lesson 2
vdmppv-xbsoftware/webix-start pull request #2
Opened 2022-04-06 14:02 UTC by vdmppv-xbsoftware

2022-04-06 23:07 UTC, HelgaListopad requested changes

2022-04-06 23:07 UTC, HelgaListopad commented on src/script.js
> +      invalidMessage: `Year should be between 1970 and ${currentYear}`
Всё-таки совсем уж простого способа менять размер `bottomPadding` под длинный текст сейчас нет.
Я покажу одно из решений (расчёт необходимой высоты для контрола, у которого есть заданное мной свойство `$customSize`). 
https://snippet.webix.com/7xi947pf

Но вот в рамках домашнего задания оно усложнит жизнь. 
Предлагаю на этом этапе просто задать лимит по ширине (`minWidth`) формы.

2022-04-06 23:07 UTC, HelgaListopad commented on src/script.js
> +  webix.ui({
Не сломается, но логически было бы правильнее поменять местами вызовы
```js
webix.ui( popupConfig );  // тут popup с id: PROFILE_POPUP_ID 
webix.ui( mainUI );       // тут любая логика, которая его задействует ( { view:"button", popup: PROFILE_POPUP_ID  } )
```

2022-04-07 08:03 UTC, vdmppv-xbsoftware commented on src/script.js
> +  webix.ui({
исправил

2022-04-07 08:03 UTC, vdmppv-xbsoftware commented on src/script.js
> +      invalidMessage: `Year should be between 1970 and ${currentYear}`
исправил

2022-04-07 09:58 UTC, HelgaListopad approved these changes

2022-04-07 10:10 UTC, fireFireee approved these changes

2022-04-07 10:10 UTC, merged