Completed Lesson 3
vdmppv-xbsoftware/webix-start pull request #3
Opened 2022-04-07 16:21 UTC by vdmppv-xbsoftware

2022-04-07 18:03 UTC, fireFireee requested changes

2022-04-07 18:03 UTC, fireFireee commented on src/dashboardView.js
> +    onAfterSelect: movieItemToForm
переименовал бы метод на то, что он делает
обычно в функциях используются глаголы, которые описывают, что делает эта функция
getValue/setValue/closeWindow/etc

для event'ов можно воспользоваться чем-то типо onAfterSelect**Handler**, хотя бы будет понятно когда эта функция вызывается

переименуй

2022-04-07 18:03 UTC, fireFireee commented on src/usersView.js
> +              var text = this.getValue().toString().toLowerCase();
1. var ???

2. не думаю, что  getValue у text'a вернёт что-то отличное от строки, поэтому , я считаю, можно удалить toString

2022-04-07 18:03 UTC, fireFireee commented on src/usersView.js
> +          click: function(){
вместо `click: function () {`

можно писать просто `click() {` если нужно сохранить контекст,
если контекст не важен, то `click: () => { ...}`

суть не меняется, но экономит место

2022-04-07 18:03 UTC, fireFireee commented on src/usersView.js
> +        onBeforeRender: function(){
почему бы не воспользоваться css'ом для этого?

даже не используя css, лучше бы вынести эту пятёрку в константу (HIGLIGHTED_ITEMS_COUNT, e.g.)
конечно с фиксированным количеством элементов париться не стоит, но с реальными данными пришлось бы ещё задуматься о том, что в лист может придти меньше пяти элементов..

2022-04-07 19:15 UTC, vdmppv-xbsoftware commented on src/dashboardView.js
> +    onAfterSelect: movieItemToForm
переименовал

2022-04-07 19:15 UTC, vdmppv-xbsoftware commented on src/usersView.js
> +              var text = this.getValue().toString().toLowerCase();
исправил

2022-04-07 19:30 UTC, vdmppv-xbsoftware commented on src/usersView.js
> +          click: function(){
исправил

2022-04-07 19:56 UTC, vdmppv-xbsoftware commented on src/usersView.js
> +        onBeforeRender: function(){
исправил

2022-04-08 08:26 UTC, fireFireee requested changes

2022-04-08 08:26 UTC, fireFireee commented on src/usersView.js
> +            if (obj.id >= 1 && obj.id <= HIGHLATED_ITEMS_AMOUNT) {
1. вариант с циклом был лучше
в реальных данных айдишка может быть больше, или совсем не числом..

2. метод find служит немного для другой цели, а не чтобы проходить по списку..
лучше воспользуйся list.data.each

** тут можно использовать this вместо $$(USER_LIST_UD),  но это вопрос вкусов

2022-04-08 09:02 UTC, vdmppv-xbsoftware commented on src/usersView.js
> +            if (obj.id >= 1 && obj.id <= HIGHLATED_ITEMS_AMOUNT) {
исправил

2022-04-08 09:09 UTC, HelgaListopad requested changes

2022-04-08 09:09 UTC, HelgaListopad commented on src/dashboardView.js
> +  url: "../data/data.js",
Все эти url (`../data`) у тебя работали?
Запрос будет делаться не отсюда, а из index.html, поэтому `../` у меня уводит запрос за пределы проекта.

2022-04-08 09:09 UTC, HelgaListopad commented on src/dashboardView.js
> +function deleteItem(){
Не используется

2022-04-08 09:09 UTC, HelgaListopad commented on src/productsView.js
> +      width: 200
Удали фиксированную ширину и добавь этой колонке `fillspace: true`, чтобы растянуть её до конца страницы и не оставлять пустого места

2022-04-08 09:09 UTC, HelgaListopad commented on src/productsView.js
> +  select: true,
По заданию значение должно быть другим
> Enable **cell** selection

2022-04-08 09:09 UTC, HelgaListopad commented on src/script.js
>        gravity: 1,
`gravity: 1` - значение для всех компонентов по умолчанию. Можно убирать

2022-04-08 09:09 UTC, HelgaListopad commented on src/usersView.js
> +      // ready() {
Неиспользованный код стоит удалить

2022-04-08 09:11 UTC, vdmppv-xbsoftware commented on src/dashboardView.js
> +  url: "../data/data.js",
работали

2022-04-08 09:11 UTC, vdmppv-xbsoftware commented on src/usersView.js
> +      // ready() {
в последнем коммите был убран

2022-04-08 09:15 UTC, vdmppv-xbsoftware commented on src/dashboardView.js
> +function deleteItem(){
исправил

2022-04-08 09:15 UTC, vdmppv-xbsoftware commented on src/productsView.js
> +      width: 200
исправил

2022-04-08 09:15 UTC, vdmppv-xbsoftware commented on src/productsView.js
> +  select: true,
исправил

2022-04-08 09:15 UTC, vdmppv-xbsoftware commented on src/script.js
>        gravity: 1,
исправил

2022-04-08 09:17 UTC, vdmppv-xbsoftware commented on src/dashboardView.js
> +  url: "../data/data.js",
но на всякий случай исправил

2022-04-08 09:26 UTC, fireFireee approved these changes

2022-04-08 11:01 UTC, HelgaListopad approved these changes

2022-04-08 11:01 UTC, merged