Completed Lesson 5
vdmppv-xbsoftware/webix-start pull request #5
Opened 2022-04-11 15:59 UTC by vdmppv-xbsoftware

2022-04-11 17:28 UTC, HelgaListopad requested changes

2022-04-11 17:28 UTC, HelgaListopad commented on src/adminView.js
> +      editAction: "click",
Значение по умолчанию точно такое же - можно не задавать

2022-04-11 17:28 UTC, HelgaListopad commented on src/dashboardView.js
> +      editor: "richSelect",
`editor:"richselect"` пишется без camelCase
Всегда есть смысл попытаться кликнуть на то, что написал - неверно названный эдитор при попытке его открыть даст ошибку.

2022-04-11 17:28 UTC, HelgaListopad commented on src/script.js
> +  $$(USER_LIST_ID).sync(usersCollection);
Чарт всё ещё синхронизирован с листом, что противоречит заданию

2022-04-11 18:46 UTC, vdmppv-xbsoftware commented on src/adminView.js
> +      editAction: "click",
исправил

2022-04-11 18:46 UTC, vdmppv-xbsoftware commented on src/dashboardView.js
> +      editor: "richSelect",
исправил

2022-04-11 18:48 UTC, vdmppv-xbsoftware commented on src/script.js
> +  $$(USER_LIST_ID).sync(usersCollection);
исправил

2022-04-12 08:12 UTC, HelgaListopad requested changes

2022-04-12 08:12 UTC, HelgaListopad commented on src/script.js
> +  $$(USER_CHART_ID).sync($$(usersCollection), () => {
Почему через `$$` ? У коллекции нет ID, по которому её нужно было бы так вызывать.
Сравни со своим же (правильным) кодом в конце файла
```js
  $$(USER_LIST_ID).sync(usersCollection);
  $$(ADMIN_VIEW_ID).sync(categoriesCollection);
```
Чтобы не путаться, хорошо было бы вызывать все sync в одной последовательности, чтобы визуально сгруппировать похожие методы. 
В моём представлении читабельнее всего расставить их от мелкого к крупному (в плане количества строк кода каждого метода)

- bind()
- all sync() calls 
- registerFilter()

2022-04-12 08:12 UTC, HelgaListopad commented on src/script.js
> +  $$(USER_LIST_ID).sync(usersCollection);
Не совсем - см. комментарий ниже

2022-04-12 09:29 UTC, vdmppv-xbsoftware commented on src/script.js
> +  $$(USER_CHART_ID).sync($$(usersCollection), () => {
Действительно, очень глупая ошибка - исправил и упорядочил методы

2022-04-12 12:53 UTC, HelgaListopad approved these changes

2022-04-12 13:53 UTC, fireFireee approved these changes

2022-04-12 13:53 UTC, merged